# =============================================================================
# Data Generation for Simulation Study
# "Semiparametric Analysis of Cure Rate Models using Soft BART"
# Mandal & Sinha, Florida State University
#
# Four simulation settings:
#
#   Sim 1 (Correctly specified):
#     h(t | W_i, x_ij) = W_i * beta * Phi(b(t,x)) * f_lambda(t)
#     W_i ~ Gamma(2, 2), N=50, n_i ~ Pois(20)+1
#
#   Sim 2 (Misspecified frailty distribution):
#     h(t | W_i, x_ij) = W_i * beta * Phi(b(t,x)) * f_lambda(t)
#     W_i ~ PS(0.8) positive stable with E[exp(-sW)] = exp(-s^0.8),
#     N=50, n_i ~ Pois(20)+1. Uses its own beta_stable (Section 2b).
#
#   Sim 3 (Misspecified frailty structure -- additive frailty):
#     h(t | W_i, x_ij) = (W_i + beta * Phi(b(t,x))) * f_lambda(t)
#     W_i ~ Gamma(kappa, kappa), E(W_i)=1, N=50, n_i ~ Pois(20)+1
#
#     Survival function:
#       S(t | W, x) = exp(-W * F_lambda(t) - beta * J(t, x))
#       where J(t,x) = integral_0^t Phi(b(u,x)) f_lambda(u) du
#
#     Cure probability:
#       pi(x | W) = exp(-W - beta * I(x))
#       where I(x) = integral_0^inf Phi(b(u,x)) f_lambda(u) du
#
#     Marginal cure via MGF of Gamma(kappa, kappa) at -1:
#       E_W[exp(-W)] = (kappa/(kappa+1))^kappa
#       pi_bar(beta) = (kappa/(kappa+1))^kappa * E_x[exp(-beta * I(x))]
#
#     SBART assumes W_i * beta multiplicative -- structurally misspecified.
#
#   Sim 4 (Small clusters):
#     h(t | W_i, x_ij) = W_i * beta * Phi(b(t,x)) * f_lambda(t)
#     W_i ~ Gamma(2, 2), N=50, n_i ~ Pois(3)+1
#
# Common parameters:
#   b(t,x) = (1.5*sin(pi*x1) - 1.0) + (3*x2 - 1.5)*(log(1+t) - 0.5)
#     - nonlinear, non-monotone baseline effect in x1 (defeats log-linear e^{x'b})
#     - time-varying effect whose SIGN flips at x2 = 0.5, producing a hazard
#       ratio that reverses over follow-up (non-proportional hazards). This is
#       the regime SBART-Cure targets and that PH/parametric competitors
#       (WGF, SGF, M-CIS) cannot represent.
#   f_lambda = Gamma(shape=2, rate=3)
#   Target: ~30% marginal cure rate, ~30% censoring among susceptibles
# =============================================================================

rm(list = ls())
set.seed(123)

library(survival)
library(ggplot2)
library(patchwork)

# =============================================================================
# SECTION 1: True model parameters
# =============================================================================

alpha_true <- 2.0    # Gamma baseline shape
theta_true <- 3.0    # Gamma baseline rate
eta_true   <- 2.0    # multiplicative frailty: W_i ~ Gamma(2,2), Var(W_i)=0.5
kappa_add  <- 1.0    # additive frailty: W_i ~ Gamma(kappa,kappa), E(W_i)=1
nu_stable  <- 0.8    # positive stable frailty index (Sim 2)

# Nonparametric regression function b(t,x) entering the hazard via Phi(b).
#   beta0(x) = 1.5*sin(pi*x1) - 1.0           nonlinear, non-monotone in x1
#   beta1(x) = 3*x2 - 1.5                      sign flips at x2 = 0.5
#   s(t)     = log(1+t) - 0.5                  sign flips at t ~ 0.65
# beta1(x)*s(t) gives a covariate effect whose direction reverses over time,
# i.e. a time-varying (non-proportional) hazard ratio. The nonlinear beta0(x)
# makes I(x)=E[Phi(b)] non-log-linear, breaking the M-CIS log-linear cure form.
b_true <- function(t, x1, x2) {
  (1.5 * sin(pi * x1) - 1.0) + (3 * x2 - 1.5) * (log(1 + t) - 0.5)
}

# Positive stable frailty W ~ PS(nu), generated by the Chambers-Mallows-Stuck
# method. The scale constant is exactly 1 for the standardized version with
# Laplace transform E[exp(-sW)] = exp(-s^nu), because
#   cos(pi*nu/2)^(1/nu) * (1 + tan(pi*nu/2)^2)^(1/(2*nu)) = 1.
# Multiplying by (1 + tan(pi*nu/2)^2)^(1/(2*nu)) instead gives the
# Samorodnitsky-Taqqu unit-scale variate, whose Laplace transform carries an
# extra sec(pi*nu/2) factor and does not match the cure formula in Section 2b.
# Threshold above which the latent competing causes are not materialised.
# W ~ PS(nu) has infinite mean, so W*beta occasionally reaches 1e12 and the
# thinning step would allocate vectors of that length. Above MAX_POIS the
# accepted minimum lies in the small-t regime where Phi(b(u,x)) is flat at
# p0 = Phi(b(0,x)) and F_lambda(t) = (theta*t)^2/2, so
#   exp(-lambda * p0 * (theta*t)^2 / 2) = U   =>   t = sqrt(-2 log U / (lambda p0)) / theta
# and T is drawn from that closed form with a single uniform. The branch is
# unreachable under Gamma frailty (Sims 1, 3, 4), where W*beta stays far below
# the threshold, so their random streams are unchanged. Only Sim 2 reaches it.
MAX_POIS <- 1e6

# Closed-form draw of the accepted minimum when the competing-cause count is
# too large to materialise. See the note on MAX_POIS above.
rmin_largelam <- function(lambda, x1s, x2s) {
  p0 <- pnorm(b_true(0, x1s, x2s))
  sqrt(-2 * log(runif(1)) / (lambda * p0)) / theta_true
}

rstable_ps <- function(n, nu = nu_stable) {
  V <- runif(n, -pi/2, pi/2)
  E <- rexp(n)
  (sin(nu * (V + pi/2)) / cos(V)^(1/nu)) *
    (cos(V - nu * (V + pi/2)) / E)^((1 - nu)/nu)
}

# =============================================================================
# SECTION 2: Calibrate beta for MULTIPLICATIVE Gamma frailty (Sims 1, 2, 4)
#
# pi_bar(beta) = E_x[(eta / (eta + beta*I(x)))^eta] = 0.30
# =============================================================================

calibrate_beta_mult <- function(target_cure = 0.30,
                                eta         = eta_true,
                                n_mc_x      = 2000,
                                n_mc_t      = 5000) {
  
  cat(sprintf("Calibrating beta (multiplicative), target cure = %.2f ...\n",
              target_cure))
  set.seed(1)
  x1_mc <- runif(n_mc_x);  x2_mc <- runif(n_mc_x)
  
  I_hat <- numeric(n_mc_x)
  for (xi in 1:n_mc_x) {
    t_mc      <- rgamma(n_mc_t, shape = alpha_true, rate = theta_true)
    I_hat[xi] <- mean(pnorm(b_true(t_mc, x1_mc[xi], x2_mc[xi])))
  }
  
  beta_grid <- seq(0.5, 10, by = 0.25)
  cure_grid <- sapply(beta_grid, function(b)
    mean((eta / (eta + b * I_hat))^eta))
  
  best_idx <- which.min(abs(cure_grid - target_cure))
  beta_opt <- beta_grid[best_idx]
  cat(sprintf("  beta = %.4f  (achieved cure = %.3f)\n",
              beta_opt, cure_grid[best_idx]))
  return(beta_opt)
}

beta_true <- calibrate_beta_mult(target_cure = 0.30, eta = eta_true)

# =============================================================================
# SECTION 2b: Calibrate beta for POSITIVE STABLE frailty (Sim 2)
#
# W ~ PS(nu) has Laplace transform E[exp(-sW)] = exp(-s^nu), so
#   pi_bar(beta) = E_x[exp(-(beta*I(x))^nu)] = 0.30
# This is a different equation from the Gamma-frailty one in Section 2, so
# beta_true does not solve it and Sim 2 requires its own calibration.
# =============================================================================

calibrate_beta_stable <- function(target_cure = 0.30,
                                  nu          = nu_stable,
                                  n_mc_x      = 2000,
                                  n_mc_t      = 5000) {

  cat(sprintf("Calibrating beta (positive stable), target cure = %.2f ...\n",
              target_cure))
  set.seed(1)
  x1_mc <- runif(n_mc_x);  x2_mc <- runif(n_mc_x)

  I_hat <- numeric(n_mc_x)
  for (xi in 1:n_mc_x) {
    t_mc      <- rgamma(n_mc_t, shape = alpha_true, rate = theta_true)
    I_hat[xi] <- mean(pnorm(b_true(t_mc, x1_mc[xi], x2_mc[xi])))
  }

  beta_grid <- seq(0.5, 10, by = 0.05)
  cure_grid <- sapply(beta_grid, function(b) mean(exp(-(b * I_hat)^nu)))

  best_idx <- which.min(abs(cure_grid - target_cure))
  beta_opt <- beta_grid[best_idx]
  cat(sprintf("  beta_stable = %.4f  (achieved cure = %.3f)\n",
              beta_opt, cure_grid[best_idx]))
  return(beta_opt)
}

beta_stable <- calibrate_beta_stable(target_cure = 0.30, nu = nu_stable)

# =============================================================================
# SECTION 3: Calibrate beta for ADDITIVE FRAILTY (Sim 3)
#
# MATHEMATICS
# -----------
# True hazard: h(t | W, x) = (W + beta * Phi(b(t,x))) * f_lambda(t)
#
# Integrating:
#   H(t | W, x) = W * F_lambda(t) + beta * J(t, x)
#   where J(t, x) = integral_0^t Phi(b(u,x)) f_lambda(u) du
#
# Survival function:
#   S(t | W, x) = exp(-W * F_lambda(t) - beta * J(t, x))
#
# Cure probability as t -> inf (F_lambda(inf)=1, J(inf,x)=I(x)):
#   pi(x | W) = exp(-W - beta * I(x))
#
# Marginal cure via MGF of Gamma(kappa, kappa) evaluated at -1:
#   E_W[exp(-W * 1)] = (kappa / (kappa + 1))^kappa
#
#   pi_bar(beta) = (kappa / (kappa + 1))^kappa * E_x[exp(-beta * I(x))]
#
# Calibration: find beta_add* = argmin |pi_bar_add(beta) - 0.30|
# =============================================================================

calibrate_beta_add <- function(target_cure = 0.30,
                               kappa       = kappa_add,
                               n_mc_x      = 2000,
                               n_mc_t      = 5000) {
  
  cat(sprintf("Calibrating beta (additive frailty), target cure = %.2f ...\n",
              target_cure))
  set.seed(1)
  x1_mc <- runif(n_mc_x);  x2_mc <- runif(n_mc_x)
  
  # Estimate I(x^(k)) = E_{T~f_lambda}[Phi(b(T,x))]
  I_hat <- numeric(n_mc_x)
  for (xi in 1:n_mc_x) {
    t_mc      <- rgamma(n_mc_t, shape = alpha_true, rate = theta_true)
    I_hat[xi] <- mean(pnorm(b_true(t_mc, x1_mc[xi], x2_mc[xi])))
  }
  
  # MGF of Gamma(kappa,kappa) at -1: E_W[exp(-W)] = (kappa/(kappa+1))^kappa
  # This does not depend on beta or I(x)
  mgf_W <- (kappa / (kappa + 1))^kappa
  
  # pi_bar(beta) = mgf_W * E_x[exp(-beta * I(x))]
  # Grid search over beta
  beta_grid <- seq(0.01, 20, by = 0.1)
  cure_grid <- sapply(beta_grid, function(b)
    mgf_W * mean(exp(-b * I_hat)))
  
  best_idx <- which.min(abs(cure_grid - target_cure))
  beta_opt <- beta_grid[best_idx]
  achieved <- cure_grid[best_idx]
  
  cat(sprintf("  beta_add = %.4f  (achieved cure = %.3f)\n", beta_opt, achieved))
  cat(sprintf("  MGF_W = (kappa/(kappa+1))^kappa = %.4f\n", mgf_W))
  return(beta_opt)
}

beta_add <- calibrate_beta_add(target_cure = 0.30, kappa = kappa_add)

# =============================================================================
# SECTION 4: Calibrate lambda_cens for ~30% censoring among susceptibles
#
# Calibrated separately under each scenario's own data-generating truth, since
# the distribution of T among susceptibles differs across the three frailty
# mechanisms. Sims 1 and 4 share the same truth (they differ only in cluster
# size, which does not affect the marginal law of T), so they share
# lambda_cens_1.
# =============================================================================

calibrate_lambda_cens <- function(target_cens = 0.30,
                                  frailty     = c("gamma", "stable", "additive"),
                                  beta        = beta_true,
                                  eta         = eta_true,
                                  kappa       = kappa_add,
                                  n_mc        = 50000,
                                  seed        = 2) {

  frailty <- match.arg(frailty)
  cat(sprintf("Calibrating lambda_cens [%s frailty], target censoring = %.2f ...\n",
              frailty, target_cens))
  set.seed(seed)

  x1_c <- runif(n_mc);  x2_c <- runif(n_mc)
  W_c  <- switch(frailty,
                 gamma    = rgamma(n_mc, shape = eta,   rate = eta),
                 stable   = rstable_ps(n_mc, nu = nu_stable),
                 additive = rgamma(n_mc, shape = kappa, rate = kappa))

  T_pop <- numeric(n_mc)
  for (s in 1:n_mc) {

    if (frailty != "additive") {
      # Multiplicative: M ~ Poisson(W*beta), each candidate thinned by Phi(b)
      lam_s <- W_c[s] * beta
      if (!is.finite(lam_s) || lam_s > MAX_POIS) {
        T_pop[s] <- rmin_largelam(min(lam_s, MAX_POIS), x1_c[s], x2_c[s])
      } else {
        M <- rpois(1, lambda = lam_s)
        if (M == 0) {
          T_pop[s] <- Inf
        } else {
          T_cand      <- rgamma(M, shape = alpha_true, rate = theta_true)
          accept_prob <- pnorm(b_true(T_cand, x1_c[s], x2_c[s]))
          accepted    <- T_cand[runif(M) < accept_prob]
          T_pop[s]    <- if (length(accepted) == 0) Inf else min(accepted)
        }
      }

    } else {
      # Additive: Part 1 = Poisson(W) unthinned, Part 2 = Poisson(beta) thinned
      M1      <- rpois(1, lambda = W_c[s])
      T_part1 <- if (M1 > 0) rgamma(M1, shape = alpha_true, rate = theta_true)
                 else numeric(0)

      M2 <- rpois(1, lambda = beta)
      if (M2 > 0) {
        T_cand2 <- rgamma(M2, shape = alpha_true, rate = theta_true)
        T_part2 <- T_cand2[runif(M2) < pnorm(b_true(T_cand2, x1_c[s], x2_c[s]))]
      } else {
        T_part2 <- numeric(0)
      }

      all_times <- c(T_part1, T_part2)
      T_pop[s]  <- if (length(all_times) == 0) Inf else min(all_times)
    }
  }

  T_susc <- T_pop[is.finite(T_pop)]
  cat(sprintf("  Population cure rate = %.3f\n", mean(!is.finite(T_pop))))

  lambda_grid <- seq(0.01, 20, by = 0.01)
  set.seed(seed + 1)
  cens_frac <- sapply(lambda_grid, function(lc)
    mean(rexp(length(T_susc), rate = lc) < T_susc))

  lambda_opt <- lambda_grid[which.min(abs(cens_frac - target_cens))]
  achieved   <- cens_frac[which.min(abs(cens_frac - target_cens))]
  cat(sprintf("  lambda_cens = %.4f  (achieved = %.3f)\n", lambda_opt, achieved))
  return(lambda_opt)
}

lambda_cens_1 <- calibrate_lambda_cens(frailty = "gamma",    beta = beta_true)    # Sims 1, 4
lambda_cens_2 <- calibrate_lambda_cens(frailty = "stable",   beta = beta_stable)  # Sim 2
lambda_cens_3 <- calibrate_lambda_cens(frailty = "additive", beta = beta_add)     # Sim 3

# Default for generate_data(); Sims 2 and 3 pass their own value explicitly.
lambda_cens_fixed <- lambda_cens_1

# =============================================================================
# SECTION 5: Single dataset generation function
#
# frailty argument:
#   "gamma"    -- multiplicative W_i*beta            (Sims 1, 4)
#   "stable"   -- multiplicative W_i*beta, W_i~S_0.8 (Sim 2)
#   "additive" -- additive (W_i + beta*Phi(b))*f_lam  (Sim 3)
#
# For "additive", pass beta_for_data = beta_add.
# For "gamma" and "stable", pass beta_for_data = beta_true.
#
# DATA GENERATION FOR SIM 3 (additive frailty)
# ---------------------------------------------
# h(t | W, x) = (W + beta * Phi(b(t,x))) * f_lambda(t)
#
# We use the thinning approach:
#   Total Poisson rate up to t: H(t|W,x) = beta*F(t) + W*J(t,x)
#   Split into two independent Poisson processes:
#     Part 1: rate beta*f_lambda(t)   -- baseline events (no Phi factor)
#     Part 2: rate W*Phi(b(t,x))*f_lambda(t) -- frailty-covariate events
#
# Part 1: M1 ~ Poisson(beta) competing causes from f_lambda (all accepted)
# Part 2: M2 ~ Poisson(W) competing causes from f_lambda, accepted w.p. Phi(b)
#
# Event time T = min of all accepted times from both parts.
# =============================================================================

generate_data <- function(N             = 50,
                          lambda_ni     = 20,
                          beta_for_data = beta_true,
                          eta           = eta_true,
                          kappa         = kappa_add,
                          frailty       = c("gamma", "stable", "additive"),
                          lambda_cens   = lambda_cens_fixed) {
  
  frailty <- match.arg(frailty)
  
  # --- Cluster sizes: n_i ~ Poisson(lambda_ni) + 1 --------------------------
  n_i     <- rpois(N, lambda = lambda_ni) + 1
  N_total <- sum(n_i)
  
  # --- Frailties W_i ---------------------------------------------------------
  if (frailty == "gamma") {
    W <- rgamma(N, shape = eta, rate = eta)
    
  } else if (frailty == "stable") {
    # Positive stable PS(nu) with E[exp(-sW)] = exp(-s^nu); see rstable_ps().
    W <- rstable_ps(N, nu = nu_stable)
    
  } else {
    # Additive: W_i ~ Gamma(kappa, kappa), E(W_i)=1, Var(W_i)=1/kappa
    W <- rgamma(N, shape = kappa, rate = kappa)
  }
  
  # --- Generate true survival times ------------------------------------------
  cluster_id <- rep(1:N, times = n_i)
  x1         <- runif(N_total)
  x2         <- runif(N_total)
  T_true     <- numeric(N_total)
  
  for (s in 1:N_total) {
    i   <- cluster_id[s]
    W_i <- W[i]
    
    if (frailty != "additive") {
      # --- Multiplicative: standard latent competing causes ------------------
      # M ~ Poisson(W_i * beta), each accepted w.p. Phi(b(T,x))
      lam_s <- W_i * beta_for_data
      if (!is.finite(lam_s) || lam_s > MAX_POIS) {
        T_true[s] <- rmin_largelam(min(lam_s, MAX_POIS), x1[s], x2[s])
      } else {
        M <- rpois(1, lambda = lam_s)
        if (M == 0) {
          T_true[s] <- Inf
        } else {
          T_cand      <- rgamma(M, shape = alpha_true, rate = theta_true)
          accept_prob <- pnorm(b_true(T_cand, x1[s], x2[s]))
          accepted    <- T_cand[runif(M) < accept_prob]
          T_true[s]   <- if (length(accepted) == 0) Inf else min(accepted)
        }
      }
      
    } else {
      # --- Additive frailty: h = (W + beta*Phi(b)) * f_lambda ---------------
      # Decompose into two independent Poisson processes:
      #
      # Part 1: rate W*f_lambda(t) -- W_i competing causes from f_lambda
      #         Each candidate accepted with probability 1 (no Phi filter)
      #         M1 ~ Poisson(W_i * F_lambda(inf)) = Poisson(W_i)
      #
      # Part 2: rate beta*Phi(b(t,x))*f_lambda(t) -- beta competing causes
      #         draw M2_raw ~ Poisson(beta), accept each w.p. Phi(b(T,x))
      #
      # T = min of all accepted times from Part 1 and Part 2
      # Subject is cured only if both parts produce zero accepted times.
      
      # Part 1: W_i frailty candidates -- all accepted (no Phi filter)
      M1 <- rpois(1, lambda = W_i)
      if (M1 > 0) {
        T_part1 <- rgamma(M1, shape = alpha_true, rate = theta_true)
      } else {
        T_part1 <- numeric(0)
      }
      
      # Part 2: beta candidates filtered by Phi(b)
      M2_raw <- rpois(1, lambda = beta_for_data)
      if (M2_raw > 0) {
        T_cand2     <- rgamma(M2_raw, shape = alpha_true, rate = theta_true)
        accept_prob <- pnorm(b_true(T_cand2, x1[s], x2[s]))
        T_part2     <- T_cand2[runif(M2_raw) < accept_prob]
      } else {
        T_part2 <- numeric(0)
      }
      
      # Combine: event time = minimum over all accepted times
      all_times <- c(T_part1, T_part2)
      T_true[s] <- if (length(all_times) == 0) Inf else min(all_times)
    }
  }
  
  # --- Censoring: C_ij ~ Exp(lambda_cens) ------------------------------------
  C_ij  <- rexp(N_total, rate = lambda_cens)
  y     <- pmin(T_true, C_ij)
  delta <- as.integer(is.finite(T_true) & T_true <= C_ij)
  y[!is.finite(T_true)] <- C_ij[!is.finite(T_true)]
  
  data.frame(
    cluster = cluster_id,
    x1      = x1,
    x2      = x2,
    y       = y,
    delta   = delta,
    W_true  = W[cluster_id],
    T_true  = ifelse(is.finite(T_true), T_true, NA_real_)
  )
}

# =============================================================================
# SECTION 6: True survival and cure probability functions
#
# Multiplicative (Sims 1, 2, 4):
#   S(t|W,x) = exp(-W*beta*J(t,x))
#   pi(x|W)  = exp(-W*beta*I(x))
#
# Additive frailty (Sim 3):
#   h(t|W,x) = (W + beta*Phi(b))*f_lambda
#   S(t|W,x) = exp(-W*F_lambda(t) - beta*J(t,x))
#   pi(x|W)  = exp(-W - beta*I(x))
#   where J(t,x) = integral_0^t Phi(b(u,x)) f_lambda(u) du
#         I(x)   = J(inf, x) = E_{T~f_lambda}[Phi(b(T,x))]
# =============================================================================

#' True conditional survival under MULTIPLICATIVE frailty
true_survival <- function(t_grid, W, x1, x2, beta, n_mc = 10000) {
  T_mc <- rgamma(n_mc, shape = alpha_true, rate = theta_true)
  sapply(t_grid, function(tg) {
    if (tg <= 0) return(1.0)
    exp(-W * beta * mean(pnorm(b_true(T_mc, x1, x2)) * (T_mc <= tg)))
  })
}

#' True conditional survival under ADDITIVE-ON-HAZARD frailty
#' S(t|W,x) = exp(-W*F_lambda(t) - beta*J(t,x))
#' J(t,x) approximated by MC: mean(Phi(b(T,x)) * (T<=t)) where T~f_lambda
true_survival_add <- function(t_grid, W, x1, x2, beta, n_mc = 10000) {
  T_mc <- rgamma(n_mc, shape = alpha_true, rate = theta_true)
  phi_mc <- pnorm(b_true(T_mc, x1, x2))
  sapply(t_grid, function(tg) {
    if (tg <= 0) return(1.0)
    F_lam_t <- mean(T_mc <= tg)                      # MC estimate of F_lambda(t)
    J_t     <- mean(phi_mc * (T_mc <= tg))            # MC estimate of J(t,x)
    exp(-W * F_lam_t - beta * J_t)
  })
}

#' True conditional cure probability under MULTIPLICATIVE frailty
true_cure_prob <- function(W, x1, x2, beta, n_mc = 5000) {
  T_mc <- rgamma(n_mc, shape = alpha_true, rate = theta_true)
  I_x  <- mean(pnorm(b_true(T_mc, x1, x2)))
  exp(-W * beta * I_x)
}

#' True conditional cure probability under ADDITIVE-ON-HAZARD frailty
#' pi(x|W) = exp(-W - beta*I(x))
#' F_lambda(inf) = 1 so the -W*F_lambda(inf) term gives -W
true_cure_prob_add <- function(W, x1, x2, beta, n_mc = 5000) {
  T_mc <- rgamma(n_mc, shape = alpha_true, rate = theta_true)
  I_x  <- mean(pnorm(b_true(T_mc, x1, x2)))
  exp(-W - beta * I_x)
}

# =============================================================================
# SECTION 7: Generate one dataset per simulation and print summaries
# =============================================================================

cat("\n=== Generating one dataset per simulation setting ===\n\n")

set.seed(42)
dat1 <- generate_data(N=50, lambda_ni=20, frailty="gamma",
                      beta_for_data=beta_true,   lambda_cens=lambda_cens_1)
dat2 <- generate_data(N=50, lambda_ni=20, frailty="stable",
                      beta_for_data=beta_stable, lambda_cens=lambda_cens_2)
dat3 <- generate_data(N=50, lambda_ni=20, frailty="additive",
                      beta_for_data=beta_add,    lambda_cens=lambda_cens_3)
dat4 <- generate_data(N=50, lambda_ni=3,  frailty="gamma",
                      beta_for_data=beta_true,   lambda_cens=lambda_cens_1)

summarize_data <- function(dat, label) {
  n_total   <- nrow(dat)
  n_clust   <- length(unique(dat$cluster))
  true_cure <- mean(is.na(dat$T_true))
  clust_sz  <- as.integer(table(dat$cluster))
  susc      <- !is.na(dat$T_true)
  
  cat(sprintf("--- %s ---\n", label))
  cat(sprintf("  N_total = %d,  clusters = %d\n", n_total, n_clust))
  cat(sprintf("  Cluster size: min=%d, median=%.0f, max=%d\n",
              min(clust_sz), median(clust_sz), max(clust_sz)))
  cat(sprintf("  True cure rate              = %.3f  (target ~0.30)\n", true_cure))
  cat(sprintf("  Event rate                  = %.3f\n", mean(dat$delta==1)))
  cat(sprintf("  Censoring (susceptibles)    = %.3f  (target ~0.30)\n",
              mean(dat$delta[susc]==0)))
  cat(sprintf("  Censoring (overall)         = %.3f\n\n", mean(dat$delta==0)))
}

summarize_data(dat1, "Sim 1: Multiplicative Gamma frailty, ni~Pois(20)+1")
summarize_data(dat2, "Sim 2: Multiplicative stable frailty, ni~Pois(20)+1")
summarize_data(dat3, "Sim 3: Additive Gamma frailty (W+beta*Phi), ni~Pois(20)+1")
summarize_data(dat4, "Sim 4: Multiplicative Gamma frailty (small), ni~Pois(3)+1")

# =============================================================================
# SECTION 8: Kaplan-Meier plots
# =============================================================================

plot_km <- function(dat, title_label) {
  km_fit    <- survfit(Surv(y, delta) ~ 1, data = dat)
  km_plat   <- tail(km_fit$surv, 1)
  true_cure <- mean(is.na(dat$T_true))
  
  km_df <- data.frame(
    time  = c(0, km_fit$time),
    surv  = c(1, km_fit$surv),
    upper = c(1, km_fit$upper),
    lower = c(1, km_fit$lower)
  )
  
  ggplot(km_df, aes(x=time, y=surv)) +
    geom_ribbon(aes(ymin=lower, ymax=upper), fill="steelblue", alpha=0.15) +
    geom_step(color="steelblue", linewidth=0.9) +
    geom_hline(yintercept=km_plat,   linetype="dashed", color="#C1292E",  linewidth=0.7) +
    geom_hline(yintercept=true_cure, linetype="dotted", color="darkgreen", linewidth=0.7) +
    annotate("text", x=max(km_df$time)*0.55, y=km_plat+0.04,
             label=sprintf("KM plateau = %.3f", km_plat),
             color="#C1292E", size=3.5) +
    annotate("text", x=max(km_df$time)*0.55, y=true_cure-0.04,
             label=sprintf("True cure  = %.3f", true_cure),
             color="darkgreen", size=3.5) +
    scale_y_continuous(limits=c(0,1), breaks=seq(0,1,0.2)) +
    labs(x="Time", y="Survival Probability", title=title_label,
         subtitle=sprintf("n=%d | clusters=%d | events=%d (%.1f%%)",
                          nrow(dat), length(unique(dat$cluster)),
                          sum(dat$delta), 100*mean(dat$delta))) +
    theme_classic(base_size=12) +
    theme(plot.title    = element_text(face="bold", hjust=0.5, size=12),
          plot.subtitle = element_text(hjust=0.5, color="grey40", size=10))
}

p1 <- plot_km(dat1, "Sim 1: Multiplicative Gamma")
p2 <- plot_km(dat2, "Sim 2: Multiplicative Stable")
p3 <- plot_km(dat3, "Sim 3: Additive Gamma Frailty")
p4 <- plot_km(dat4, "Sim 4: Small Clusters")

p_combined <- (p1 + p2) / (p3 + p4) +
  plot_annotation(
    title   = "Kaplan-Meier Curves by Simulation Setting",
    caption = "Red dashed = KM plateau  |  Green dotted = True cure rate",
    theme   = theme(plot.title   = element_text(face="bold", hjust=0.5, size=14),
                    plot.caption = element_text(hjust=0.5, color="grey40"))
  )
print(p_combined)

# =============================================================================
# SECTION 9: Generate R replicates for the full simulation study
# =============================================================================

generate_replicates <- function(R = 100, sim = 1, seed = 123) {
  
  settings <- list(
    `1` = list(N=50, lambda_ni=20, frailty="gamma",    beta_d=beta_true,   lam=lambda_cens_1),
    `2` = list(N=50, lambda_ni=20, frailty="stable",   beta_d=beta_stable, lam=lambda_cens_2),
    `3` = list(N=50, lambda_ni=20, frailty="additive", beta_d=beta_add,    lam=lambda_cens_3),
    `4` = list(N=50, lambda_ni=3,  frailty="gamma",    beta_d=beta_true,   lam=lambda_cens_1)
  )
  s <- settings[[as.character(sim)]]
  
  cat(sprintf("Generating %d replicates for Simulation %d...\n", R, sim))
  set.seed(seed)
  
  replicates <- vector("list", R)
  for (r in 1:R) {
    replicates[[r]] <- generate_data(
      N             = s$N,
      lambda_ni     = s$lambda_ni,
      frailty       = s$frailty,
      beta_for_data = s$beta_d,
      lambda_cens   = s$lam
    )
    if (r %% 10 == 0) cat(sprintf("  Replicate %d / %d\n", r, R))
  }
  cat("Done.\n")
  return(replicates)
}

# --- Run when ready ----------------------------------------------------------
# replicates_sim1 <- generate_replicates(R=100, sim=1)
# replicates_sim2 <- generate_replicates(R=100, sim=2)
# replicates_sim3 <- generate_replicates(R=100, sim=3)
# replicates_sim4 <- generate_replicates(R=100, sim=4)